let witnesses = []

// this function will be used to return a copy of the ARRAY generated by
//  getCriminals() over on main.js
export const useWitnesses= () => {
    
    return witnesses.slice()
}



export const getWitnesses = () => {
    return fetch("https://criminals.glassdale.us/witnesses")
        .then(response => response.json())
        .then(
            parsedWitnesses => {
                // console.table(parsedCriminals)
                witnesses = parsedWitnesses
                // console.log(witnesses)
            }
        )
}

