// this empty array get's the fucking party started
let criminals = []

// this function will be used to return a copy of the TABLE generated by
//  getCriminals() over on main.js
export const useCriminals = () => {
    return criminals.slice()
}

// this badass-mother-function (is this shit A-SYNCHRONUS?) 
// asks the interwebs to go to a specific web address
// and FETCH IT, then (i think) we get a "response" (keyword) then slap some
// .json() on it to be able to use .table() (method?) to return a sweet
// table full of criminales 

export const getCriminals = () => {
    return fetch("https://criminals.glassdale.us/criminals")
        .then(response => response.json())
        .then(
            parsedCriminals => {
                console.table(parsedCriminals)
                criminals = parsedCriminals
            }
        )
}



// STARTER CODE BELOW
// let criminals = []

// export const useCriminals = () => criminals.slice()

// export const getCriminals = () => {
//     /*
//         Load database state into application state with a fetch().
//         Make sure the last then() updates the criminals array
//     */
// }